trigger:
  - production

pool:
  name: 'self-hosted-agent-01'  # Self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  sourceDir: '$(Build.SourcesDirectory)/1/source'  # Path to your source code

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build project'

  # Ensure the build output exists before publishing
  - script: |
      echo "Listing files in build output directory"
      dir $(Build.ArtifactStagingDirectory)
    displayName: 'Check Artifact Directory'

  # Publish the build output as an artifact
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: 'drop'
    displayName: 'Publish Build Artifact'
