trigger:
  - production

pool:
  name: self-hosted-agent-01

variables:
  buildConfiguration: 'Release'  # Consistent use of single quotes

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build project'
